int _putchar(char);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int);
int _isalpha(int);
int print_sign(int);
int _abs(int);
int print_last_digit(int);
void jack_bauer(void);
int get_first(int);
int get_last(int);
void times_table(void);
int add(int, int);
void print_any_int(int);
void print_to_98(int);
void print_times_table(int);
long get_first_l(long);
